// Queue
#define LIST_QUEUE_CAR_RENTAL 1
#define LIST_QUEUE_TERMINAL_1 2
#define LIST_QUEUE_TERMINAL_2 3
#define LIST_BUS_TO_CAR_RENTAL 4
#define LIST_BUS_TO_TERMINAL_1 5
#define LIST_BUS_TO_TERMINAL_2 6